// Code generated by oapi-codegen. DO NOT EDIT.

package petstore

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type PetNicknames string

const (
	Fluffy PetNicknames = "Fluffy"
	Rover  PetNicknames = "Rover"
	Spot   PetNicknames = "Spot"
)

// Validate checks if the PetNicknames value is valid
func (p PetNicknames) Validate() error {
	switch p {
	case Fluffy, Rover, Spot:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid PetNicknames value, got: %v", p))
	}
}

type GetPetPath struct {
	PetID string `json:"petId" validate:"required"`
}

func (g GetPetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type CreatePetBody = PetModel

type ListPetsResponse []PetModel

type CreatePetResponse = PetModel

type GetPetResponse = PetModel

type PetModel struct {
	PetID *int64  `json:"id,omitempty"`
	Name  string  `json:"name" validate:"required"`
	Tag   *string `json:"tag,omitempty"`

	// Nicknames Alternative names for the pet
	Nicknames []PetNicknames `json:"nicknames,omitempty"`
}

func (p PetModel) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(p.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	for i, item := range p.Nicknames {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Nicknames[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
