app:
  port: 2200
  disableUI: false
  disableSwaggerUI: false
  editor:
    theme: chrome
    fontSize: 16

services:
  adyen:
    errors:
      p100: 500

  blik:
    latency: 2s
    errors:
      p10: 500

  stripe:
    latency: 123ms
