// Code generated by gen-service. DO NOT EDIT.

package handler

import (
	"sync"

	"github.com/cubahno/connexions/v2/pkg/api"
	"github.com/cubahno/connexions/v2/pkg/generator"
	"github.com/cubahno/connexions/v2/pkg/schema"
	"github.com/cubahno/connexions/v2/pkg/typedef"
)

// ResponseData wraps the generated response.
type ResponseData struct {
	Body    []byte
	Headers map[string][]string
	IsError bool
}

// serviceInterface defines the interface for mock generation.
type serviceInterface interface {
	addPet(path, method string) (*ResponseData, error)
	updatePet(path, method string) (*ResponseData, error)
	findPetsByStatus(path, method string) (*ResponseData, error)
	findPetsByTags(path, method string) (*ResponseData, error)
	getPetByID(path, method string) (*ResponseData, error)
	updatePetWithForm(path, method string) (*ResponseData, error)
	deletePet(path, method string) (*ResponseData, error)
	uploadFile(path, method string) (*ResponseData, error)
	getInventory(path, method string) (*ResponseData, error)
	placeOrder(path, method string) (*ResponseData, error)
	getOrderByID(path, method string) (*ResponseData, error)
	deleteOrder(path, method string) (*ResponseData, error)
	createUser(path, method string) (*ResponseData, error)
	createUsersWithListInput(path, method string) (*ResponseData, error)
	loginUser(path, method string) (*ResponseData, error)
	logoutUser(path, method string) (*ResponseData, error)
	getUserByName(path, method string) (*ResponseData, error)
	updateUser(path, method string) (*ResponseData, error)
	deleteUser(path, method string) (*ResponseData, error)
	generateRequest(req *api.GenerateRequest, op *schema.Operation) []byte
	generateError(path, method string, errMsg string) []byte
}

// operationData holds cached operation and response schema for a single endpoint.
type operationData struct {
	operation      *schema.Operation
	responseSchema *schema.ResponseSchema
}

// service implements serviceInterface with mock generation logic.
type service struct {
	generator generator.Generate
	registry  typedef.OperationRegistry

	// Cached operation data (lazy loaded)
	opCache sync.Map // map[string]*operationData
}

// newService creates a new service instance.
func newService(contextsSrc []byte, defaultContexts []map[string]map[string]any, registry typedef.OperationRegistry) (*service, error) {
	orderedCtx := generator.LoadServiceContext(contextsSrc, defaultContexts)

	gen, err := generator.NewGenerator(orderedCtx)
	if err != nil {
		return nil, err
	}

	return &service{
		generator: gen,
		registry:  registry,
	}, nil
}

// Ensure service implements serviceInterface.
var _ serviceInterface = (*service)(nil)

// getOperationData returns cached operation data, loading it lazily if needed.
func (s *service) getOperationData(path, method string) *operationData {
	key := method + ":" + path

	// Check cache first
	if cached, ok := s.opCache.Load(key); ok {
		return cached.(*operationData)
	}

	// Load from registry
	op := s.registry.FindOperation(path, method)
	if op == nil {
		return nil
	}

	// Build response schema
	respSchema := &schema.ResponseSchema{}
	if successResp := op.Response.GetSuccess(); successResp != nil {
		respSchema.ContentType = successResp.ContentType
		respSchema.Body = successResp.Content
		respSchema.Headers = successResp.Headers
	}
	if errResp := op.Response.GetResponse(400); errResp != nil {
		respSchema.Error = errResp.Content
	}

	data := &operationData{
		operation:      op,
		responseSchema: respSchema,
	}

	s.opCache.Store(key, data)
	return data
}

func (s *service) generateRequest(req *api.GenerateRequest, op *schema.Operation) []byte {
	if op == nil {
		opData := s.getOperationData(req.Path, req.Method)
		if opData != nil {
			op = opData.operation
		}
	}
	return s.generator.Request(req, op)
}

func (s *service) generateError(path, method string, errMsg string) []byte {
	opData := s.getOperationData(path, method)
	if opData != nil && opData.responseSchema.Error != nil {
		opKey := method + ":" + path
		return s.generator.Error(opData.responseSchema.Error, errorPaths[opKey], errMsg)
	}
	return []byte(errMsg)
}

func (s *service) addPet(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) updatePet(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) findPetsByStatus(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) findPetsByTags(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getPetByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) updatePetWithForm(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) deletePet(path, method string) (*ResponseData, error) {
	return &ResponseData{}, nil
}

func (s *service) uploadFile(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getInventory(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) placeOrder(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getOrderByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) deleteOrder(path, method string) (*ResponseData, error) {
	return &ResponseData{}, nil
}

func (s *service) createUser(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) createUsersWithListInput(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) loginUser(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) logoutUser(path, method string) (*ResponseData, error) {
	return &ResponseData{}, nil
}

func (s *service) getUserByName(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) updateUser(path, method string) (*ResponseData, error) {
	return &ResponseData{}, nil
}

func (s *service) deleteUser(path, method string) (*ResponseData, error) {
	return &ResponseData{}, nil
}
