# yaml-language-server: $schema=https://raw.githubusercontent.com/cubahno/connexions/refs/heads/master/resources/json-schema-service.json
name: zero
latency: 0ms
errors:
#  p10: 500
#  p20: 400
#generate:
#  server: {}
cache:
  requests: true
validate:
  request: true
  response: false
spec:
  simplify: false
  # optional-properties not set = keep all optional properties
  # optional-properties:
  #   min: 5
  #   max: 5
