// Code generated by oapi-codegen. DO NOT EDIT.

package types

type VisualizeRecipeTasteHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
	Accept      *Accept      `json:"Accept,omitempty"`
}

type VisualizeRecipeNutritionHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
	Accept      *Accept      `json:"Accept,omitempty"`
}

type VisualizePriceBreakdownHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
	Accept      *Accept      `json:"Accept,omitempty"`
}

type VisualizeEquipmentHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
	Accept      *Accept      `json:"Accept,omitempty"`
}

type CreateRecipeCardHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
}

type AnalyzeRecipeInstructionsHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
}

type ClassifyCuisineHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
}

type ParseIngredientsHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
}

type VisualizeRecipeNutritionByIDHeaders struct {
	Accept *Accept `json:"Accept,omitempty"`
}

type VisualizeIngredientsHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
	Accept      *Accept      `json:"Accept,omitempty"`
}

type VisualizeProductNutritionByIDHeaders struct {
	Accept *Accept `json:"Accept,omitempty"`
}

type VisualizeMenuItemNutritionByIDHeaders struct {
	Accept *Accept `json:"Accept,omitempty"`
}

type DetectFoodInTextHeaders struct {
	ContentType *ContentType `json:"Content-Type,omitempty"`
}
