// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type VisualizeRecipeTasteBody = string

type VisualizeRecipeNutritionBody = string

type VisualizePriceBreakdownBody = string

type VisualizeEquipmentBody = string

type AnalyzeRecipeBody struct {
	Language         *string `json:"language,omitempty"`
	IncludeNutrition *bool   `json:"includeNutrition,omitempty"`
	IncludeTaste     *bool   `json:"includeTaste,omitempty"`
}

type CreateRecipeCardBody = string

type AnalyzeRecipeInstructionsBody = string

type ClassifyCuisineBody = string

type ParseIngredientsBody = string

type VisualizeIngredientsBody = string

type ComputeGlycemicLoadBody struct {
	Ingredients []string `json:"ingredients" validate:"required"`
}

func (c ComputeGlycemicLoadBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type ClassifyGroceryProductBody struct {
	Title   string `json:"title" validate:"required,min=1"`
	Upc     string `json:"upc" validate:"required"`
	PluCode string `json:"plu_code" validate:"required"`
}

func (c ClassifyGroceryProductBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type ClassifyGroceryProductBulkBody []ClassifyGroceryProductBulkBody_Item

func (c ClassifyGroceryProductBulkBody) Validate() error {
	if c == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	if len(c) < 0 {
		errors = errors.Add("Array", fmt.Sprintf("must have at least 0 items, got %d", len(c)))
	}
	for i, item := range c {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type MapIngredientsToGroceryProductsBody struct {
	Ingredients []string `json:"ingredients" validate:"required"`
	Servings    float32  `json:"servings" validate:"required"`
}

func (m MapIngredientsToGroceryProductsBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(m))
}

type ClearMealPlanDayBody struct {
	Username string `json:"username" validate:"required"`
	Date     string `json:"date" validate:"required"`
	Hash     string `json:"hash" validate:"required"`
}

func (c ClearMealPlanDayBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type AddToMealPlanBody struct {
	Username string `json:"username" validate:"required"`
	Hash     string `json:"hash" validate:"required"`
}

func (a AddToMealPlanBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}

type DeleteFromMealPlanBody struct {
	Username string  `json:"username" validate:"required"`
	ID       float32 `json:"id" validate:"required"`
	Hash     string  `json:"hash" validate:"required"`
}

func (d DeleteFromMealPlanBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type AddMealPlanTemplateBody struct {
	Username string `json:"username" validate:"required"`
	Hash     string `json:"hash" validate:"required"`
}

func (a AddMealPlanTemplateBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}

type DeleteMealPlanTemplateBody struct {
	Username string  `json:"username" validate:"required"`
	ID       float32 `json:"id" validate:"required"`
	Hash     string  `json:"hash" validate:"required"`
}

func (d DeleteMealPlanTemplateBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type GenerateShoppingListBody struct {
	Username  string `json:"username" validate:"required"`
	StartDate string `json:"start-date" validate:"required"`
	EndDate   string `json:"end-date" validate:"required"`
	Hash      string `json:"hash" validate:"required"`
}

func (g GenerateShoppingListBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type ConnectUserBody = map[string]any

type AddToShoppingListBody struct {
	Username string `json:"username" validate:"required"`
	Hash     string `json:"hash" validate:"required"`
}

func (a AddToShoppingListBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}

type DeleteFromShoppingListBody struct {
	Username string  `json:"username" validate:"required"`
	ID       float32 `json:"id" validate:"required"`
	Hash     string  `json:"hash" validate:"required"`
}

func (d DeleteFromShoppingListBody) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type DetectFoodInTextBody = string
