// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type Language string

const (
	LanguageDe Language = "de"
	LanguageEn Language = "en"
)

// Validate checks if the Language value is valid
func (l Language) Validate() error {
	switch l {
	case LanguageDe, LanguageEn:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid Language value, got: %v", l))
	}
}

type ContentType string

const (
	ContentTypeApplicationJSON               ContentType = "application/json"
	ContentTypeApplicationXWwwFormUrlencoded ContentType = "application/x-www-form-urlencoded"
	ContentTypeMultipartFormData             ContentType = "multipart/form-data"
)

// Validate checks if the ContentType value is valid
func (c ContentType) Validate() error {
	switch c {
	case ContentTypeApplicationJSON, ContentTypeApplicationXWwwFormUrlencoded, ContentTypeMultipartFormData:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ContentType value, got: %v", c))
	}
}

type Accept string

const (
	AcceptApplicationJSON Accept = "application/json"
	AcceptMedia           Accept = "media/*"
	AcceptTextHTML        Accept = "text/html"
)

// Validate checks if the Accept value is valid
func (a Accept) Validate() error {
	switch a {
	case AcceptApplicationJSON, AcceptMedia, AcceptTextHTML:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid Accept value, got: %v", a))
	}
}

type GetRecipeTasteByIDQueryNormalize bool

const (
	GetRecipeTasteByIDQueryNormalizeFalse GetRecipeTasteByIDQueryNormalize = false
	GetRecipeTasteByIDQueryNormalizeTrue  GetRecipeTasteByIDQueryNormalize = true
)

// Validate checks if the GetRecipeTasteByIDQueryNormalize value is valid
func (g GetRecipeTasteByIDQueryNormalize) Validate() error {
	switch g {
	case GetRecipeTasteByIDQueryNormalizeFalse, GetRecipeTasteByIDQueryNormalizeTrue:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid GetRecipeTasteByIDQueryNormalize value, got: %v", g))
	}
}

type IngredientsByIDImageQueryMeasure string

const (
	IngredientsByIDImageQueryMeasureMetric IngredientsByIDImageQueryMeasure = "metric"
	IngredientsByIDImageQueryMeasureUs     IngredientsByIDImageQueryMeasure = "us"
)

// Validate checks if the IngredientsByIDImageQueryMeasure value is valid
func (i IngredientsByIDImageQueryMeasure) Validate() error {
	switch i {
	case IngredientsByIDImageQueryMeasureMetric, IngredientsByIDImageQueryMeasureUs:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid IngredientsByIDImageQueryMeasure value, got: %v", i))
	}
}

type VisualizeRecipeIngredientsByIDQueryMeasure string

const (
	VisualizeRecipeIngredientsByIDQueryMeasureMetric VisualizeRecipeIngredientsByIDQueryMeasure = "metric"
	VisualizeRecipeIngredientsByIDQueryMeasureUs     VisualizeRecipeIngredientsByIDQueryMeasure = "us"
)

// Validate checks if the VisualizeRecipeIngredientsByIDQueryMeasure value is valid
func (v VisualizeRecipeIngredientsByIDQueryMeasure) Validate() error {
	switch v {
	case VisualizeRecipeIngredientsByIDQueryMeasureMetric, VisualizeRecipeIngredientsByIDQueryMeasureUs:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid VisualizeRecipeIngredientsByIDQueryMeasure value, got: %v", v))
	}
}

type VisualizeRecipeTasteByIDQueryNormalize bool

const (
	VisualizeRecipeTasteByIDQueryNormalizeFalse VisualizeRecipeTasteByIDQueryNormalize = false
	VisualizeRecipeTasteByIDQueryNormalizeTrue  VisualizeRecipeTasteByIDQueryNormalize = true
)

// Validate checks if the VisualizeRecipeTasteByIDQueryNormalize value is valid
func (v VisualizeRecipeTasteByIDQueryNormalize) Validate() error {
	switch v {
	case VisualizeRecipeTasteByIDQueryNormalizeFalse, VisualizeRecipeTasteByIDQueryNormalizeTrue:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid VisualizeRecipeTasteByIDQueryNormalize value, got: %v", v))
	}
}

type SearchGroceryProductsQueryAddProductInformation bool

const (
	SearchGroceryProductsQueryAddProductInformationFalse SearchGroceryProductsQueryAddProductInformation = false
	SearchGroceryProductsQueryAddProductInformationTrue  SearchGroceryProductsQueryAddProductInformation = true
)

// Validate checks if the SearchGroceryProductsQueryAddProductInformation value is valid
func (s SearchGroceryProductsQueryAddProductInformation) Validate() error {
	switch s {
	case SearchGroceryProductsQueryAddProductInformationFalse, SearchGroceryProductsQueryAddProductInformationTrue:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid SearchGroceryProductsQueryAddProductInformation value, got: %v", s))
	}
}

type ClassifyGroceryProductQueryLocale string

const (
	ClassifyGroceryProductQueryLocaleEnGB ClassifyGroceryProductQueryLocale = "en_GB"
	ClassifyGroceryProductQueryLocaleEnUS ClassifyGroceryProductQueryLocale = "en_US"
)

// Validate checks if the ClassifyGroceryProductQueryLocale value is valid
func (c ClassifyGroceryProductQueryLocale) Validate() error {
	switch c {
	case ClassifyGroceryProductQueryLocaleEnGB, ClassifyGroceryProductQueryLocaleEnUS:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ClassifyGroceryProductQueryLocale value, got: %v", c))
	}
}

type SearchMenuItemsQueryAddMenuItemInformation bool

const (
	SearchMenuItemsQueryAddMenuItemInformationFalse SearchMenuItemsQueryAddMenuItemInformation = false
	SearchMenuItemsQueryAddMenuItemInformationTrue  SearchMenuItemsQueryAddMenuItemInformation = true
)

// Validate checks if the SearchMenuItemsQueryAddMenuItemInformation value is valid
func (s SearchMenuItemsQueryAddMenuItemInformation) Validate() error {
	switch s {
	case SearchMenuItemsQueryAddMenuItemInformationFalse, SearchMenuItemsQueryAddMenuItemInformationTrue:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid SearchMenuItemsQueryAddMenuItemInformation value, got: %v", s))
	}
}
