// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type ID = int64

type Username = string

type GetRecipeInformationPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetRecipeInformationPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetSimilarRecipesPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetSimilarRecipesPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetRecipeTasteByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetRecipeTasteByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type RecipeTasteByIDImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (r RecipeTasteByIDImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(r))
}

type GetRecipeEquipmentByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetRecipeEquipmentByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type EquipmentByIDImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (e EquipmentByIDImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(e))
}

type GetRecipePriceBreakdownByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetRecipePriceBreakdownByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type PriceBreakdownByIDImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (p PriceBreakdownByIDImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type GetRecipeIngredientsByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetRecipeIngredientsByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type IngredientsByIDImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (i IngredientsByIDImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(i))
}

type GetRecipeNutritionWidgetByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetRecipeNutritionWidgetByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type RecipeNutritionByIDImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (r RecipeNutritionByIDImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(r))
}

type RecipeNutritionLabelWidgetPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (r RecipeNutritionLabelWidgetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(r))
}

type RecipeNutritionLabelImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (r RecipeNutritionLabelImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(r))
}

type GetAnalyzedRecipeInstructionsPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetAnalyzedRecipeInstructionsPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type VisualizeRecipeIngredientsByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (v VisualizeRecipeIngredientsByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(v))
}

type VisualizeRecipeTasteByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (v VisualizeRecipeTasteByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(v))
}

type VisualizeRecipeEquipmentByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (v VisualizeRecipeEquipmentByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(v))
}

type VisualizeRecipePriceBreakdownByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (v VisualizeRecipePriceBreakdownByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(v))
}

type SummarizeRecipePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (s SummarizeRecipePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(s))
}

type CreateRecipeCardGetPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (c CreateRecipeCardGetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type VisualizeRecipeNutritionByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (v VisualizeRecipeNutritionByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(v))
}

type GetIngredientInformationPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetIngredientInformationPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type ComputeIngredientAmountPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (c ComputeIngredientAmountPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type GetIngredientSubstitutesByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetIngredientSubstitutesByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type SearchGroceryProductsByUPCPath struct {
	Upc float32 `json:"upc" validate:"required"`
}

func (s SearchGroceryProductsByUPCPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(s))
}

type GetProductInformationPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetProductInformationPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GetComparableProductsPath struct {
	Upc float32 `json:"upc" validate:"required"`
}

func (g GetComparableProductsPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type VisualizeProductNutritionByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (v VisualizeProductNutritionByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(v))
}

type ProductNutritionByIDImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (p ProductNutritionByIDImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type ProductNutritionLabelWidgetPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (p ProductNutritionLabelWidgetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type ProductNutritionLabelImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (p ProductNutritionLabelImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(p))
}

type GetMenuItemInformationPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (g GetMenuItemInformationPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type VisualizeMenuItemNutritionByIDPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (v VisualizeMenuItemNutritionByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(v))
}

type MenuItemNutritionByIDImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (m MenuItemNutritionByIDImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(m))
}

type MenuItemNutritionLabelWidgetPath struct {
	ID float32 `json:"id" validate:"required"`
}

func (m MenuItemNutritionLabelWidgetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(m))
}

type MenuItemNutritionLabelImagePath struct {
	ID float32 `json:"id" validate:"required"`
}

func (m MenuItemNutritionLabelImagePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(m))
}

type GetMealPlanWeekPath struct {
	Username  string `json:"username" validate:"required"`
	StartDate string `json:"start-date" validate:"required"`
}

func (g GetMealPlanWeekPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type ClearMealPlanDayPath struct {
	Username string `json:"username" validate:"required"`
	Date     string `json:"date" validate:"required"`
}

func (c ClearMealPlanDayPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(c))
}

type AddToMealPlanPath struct {
	Username string `json:"username" validate:"required"`
}

func (a AddToMealPlanPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}

type DeleteFromMealPlanPath struct {
	Username string  `json:"username" validate:"required"`
	ID       float32 `json:"id" validate:"required"`
}

func (d DeleteFromMealPlanPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type GetMealPlanTemplatesPath struct {
	Username string `json:"username" validate:"required"`
}

func (g GetMealPlanTemplatesPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type AddMealPlanTemplatePath struct {
	Username string `json:"username" validate:"required"`
}

func (a AddMealPlanTemplatePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}

type GetMealPlanTemplatePath struct {
	Username string  `json:"username" validate:"required"`
	ID       float32 `json:"id" validate:"required"`
}

func (g GetMealPlanTemplatePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type DeleteMealPlanTemplatePath struct {
	Username string  `json:"username" validate:"required"`
	ID       float32 `json:"id" validate:"required"`
}

func (d DeleteMealPlanTemplatePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type GetShoppingListPath struct {
	Username string `json:"username" validate:"required"`
}

func (g GetShoppingListPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type GenerateShoppingListPath struct {
	Username  string `json:"username" validate:"required"`
	StartDate string `json:"start-date" validate:"required"`
	EndDate   string `json:"end-date" validate:"required"`
}

func (g GenerateShoppingListPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type AddToShoppingListPath struct {
	Username string `json:"username" validate:"required"`
}

func (a AddToShoppingListPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(a))
}

type DeleteFromShoppingListPath struct {
	Username string  `json:"username" validate:"required"`
	ID       float32 `json:"id" validate:"required"`
}

func (d DeleteFromShoppingListPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}
