// Code generated by connexions setup. DO NOT EDIT.

package petstore

import (
	_ "embed"
	"fmt"
	"log/slog"

	"example/services/petstore/handler"

	"github.com/cubahno/connexions/v2/pkg/api"
	"github.com/cubahno/connexions/v2/pkg/config"
	"github.com/cubahno/connexions/v2/pkg/loader"
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/codegen"
	"go.yaml.in/yaml/v4"
)

//go:embed setup/config.yml
var configSrc []byte

//go:embed setup/context.yml
var contextSrc []byte

//go:embed setup/openapi.*
var openapiSpec []byte

//go:embed setup/codegen.yml
var codegenConfigSrc []byte

const serviceName = "petstore"

// Register registers the Petstore service with the central router.
// This function is called automatically during service discovery.
func Register(router *api.Router) {
	cfg, err := config.NewServiceConfigFromBytes(configSrc)
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to parse config for %s", serviceName),
			"error", err,
			"service", serviceName,
		)
		return
	}

	// Load codegen config to apply the same filtering at runtime
	var codegenCfg codegen.Configuration
	if err := yaml.Unmarshal(codegenConfigSrc, &codegenCfg); err != nil {
		slog.Error(fmt.Sprintf("Failed to parse codegen config for %s", serviceName),
			"error", err,
			"service", serviceName,
		)
		return
	}
	codegenCfg = codegenCfg.Merge(codegen.NewDefaultConfiguration())

	// Create the typedef registry from the OpenAPI spec
	// Pass the codegen config so it applies the same filtering (e.g., only parse needed operations)
	registry := handler.NewRegistry(openapiSpec, codegenCfg, cfg.SpecOptions)

	// Create handler
	h, err := handler.New(contextSrc, router.GetContexts(), config.NewHandlerConfig(cfg), registry)
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create handler for %s", serviceName),
			"error", err,
			"service", serviceName,
		)
		return
	}

	// Get service-specific middleware
	serviceMiddleware := getMiddleware()

	// Register service with router
	router.RegisterService(cfg, h, serviceMiddleware)

	// Log registration
	routes := h.Routes()
	slog.Info(fmt.Sprintf("Registered %d routes for %s service", len(routes), serviceName),
		"routes", len(routes),
		"service", serviceName,
	)
}

func init() {
	// Auto-register this service with the loader registry
	loader.Register(serviceName, Register)
}
