// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type OrderStatus string

const (
	OrderStatusApproved  OrderStatus = "approved"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusPlaced    OrderStatus = "placed"
)

// Validate checks if the OrderStatus value is valid
func (o OrderStatus) Validate() error {
	switch o {
	case OrderStatusApproved, OrderStatusDelivered, OrderStatusPlaced:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid OrderStatus value, got: %v", o))
	}
}

type PetStatus string

const (
	PetStatusAvailable PetStatus = "available"
	PetStatusPending   PetStatus = "pending"
	PetStatusSold      PetStatus = "sold"
)

// Validate checks if the PetStatus value is valid
func (p PetStatus) Validate() error {
	switch p {
	case PetStatusAvailable, PetStatusPending, PetStatusSold:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid PetStatus value, got: %v", p))
	}
}

type FindPetsByStatusQueryStatus string

const (
	FindPetsByStatusQueryStatusAvailable FindPetsByStatusQueryStatus = "available"
	FindPetsByStatusQueryStatusPending   FindPetsByStatusQueryStatus = "pending"
	FindPetsByStatusQueryStatusSold      FindPetsByStatusQueryStatus = "sold"
)

// Validate checks if the FindPetsByStatusQueryStatus value is valid
func (f FindPetsByStatusQueryStatus) Validate() error {
	switch f {
	case FindPetsByStatusQueryStatusAvailable, FindPetsByStatusQueryStatusPending, FindPetsByStatusQueryStatusSold:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid FindPetsByStatusQueryStatus value, got: %v", f))
	}
}
