// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type UpdatePetBody = Pet

type AddPetBody = Pet

type UploadFileBody = runtime.File

type PlaceOrderBody = Order

type CreateUserBody = User

type CreateUsersWithListInputBody []User

func (c CreateUsersWithListInputBody) Validate() error {
	if c == nil {
		return nil
	}
	var errors runtime.ValidationErrors
	for i, item := range c {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("[%d]", i), err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateUserBody = User
