// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type FindPetsByStatusQuery struct {
	Status FindPetsByStatusQueryStatus `json:"status" validate:"required"`
}

func (f FindPetsByStatusQuery) Validate() error {
	var errors runtime.ValidationErrors
	if v, ok := any(f.Status).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Status", err)
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type FindPetsByTagsQuery struct {
	Tags []string `json:"tags" validate:"required"`
}

func (f FindPetsByTagsQuery) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(f))
}

type UpdatePetWithFormQuery struct {
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

type UploadFileQuery struct {
	AdditionalMetadata *string `json:"additionalMetadata,omitempty"`
}

type LoginUserQuery struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}
