// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"fmt"
	"time"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type Order struct {
	ID       *int64       `json:"id,omitempty"`
	PetID    *int64       `json:"petId,omitempty"`
	Quantity *int32       `json:"quantity,omitempty"`
	ShipDate *time.Time   `json:"shipDate,omitempty"`
	Status   *OrderStatus `json:"status,omitempty"`
	Complete *bool        `json:"complete,omitempty"`
}

func (o Order) Validate() error {
	var errors runtime.ValidationErrors
	if o.Status != nil {
		if v, ok := any(o.Status).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Status", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Category struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type User struct {
	ID         *int64  `json:"id,omitempty"`
	Username   *string `json:"username,omitempty"`
	FirstName  *string `json:"firstName,omitempty"`
	LastName   *string `json:"lastName,omitempty"`
	Email      *string `json:"email,omitempty"`
	Password   *string `json:"password,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	UserStatus *int32  `json:"userStatus,omitempty"`
}

type Tag struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type Pet struct {
	ID        *int64     `json:"id,omitempty"`
	Name      string     `json:"name" validate:"required"`
	Category  *Category  `json:"category,omitempty"`
	PhotoUrls []string   `json:"photoUrls" validate:"required"`
	Tags      []Tag      `json:"tags,omitempty"`
	Status    *PetStatus `json:"status,omitempty"`
}

func (p Pet) Validate() error {
	var errors runtime.ValidationErrors
	if err := typesValidator.Var(p.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if p.Category != nil {
		if v, ok := any(p.Category).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Category", err)
			}
		}
	}
	if err := typesValidator.Var(p.PhotoUrls, "required"); err != nil {
		errors = errors.Append("PhotoUrls", err)
	}
	for i, item := range p.Tags {
		if v, ok := any(item).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append(fmt.Sprintf("Tags[%d]", i), err)
			}
		}
	}
	if p.Status != nil {
		if v, ok := any(p.Status).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Status", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type APIResponse struct {
	Code    *int32  `json:"code,omitempty"`
	Type    *string `json:"type,omitempty"`
	Message *string `json:"message,omitempty"`
}
