package api

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cubahno/connexions/v2/internal/files"
	"github.com/cubahno/connexions/v2/pkg/config"
)

// DiscoverOptions contains options for discovering services.
type DiscoverOptions struct {
	// Optional: services directory to scan
	ServicesDir string

	// Optional: output file path (default: cmd/server/services_gen.go)
	OutputFile string
}

// Discover scans the services directory and generates an imports file.
func Discover(opts DiscoverOptions) error {
	serviceDir := opts.ServicesDir
	if serviceDir == "" {
		paths := config.NewPaths("")
		serviceDir = paths.Services
	}

	serviceDirAbs, err := filepath.Abs(serviceDir)
	if err != nil {
		return fmt.Errorf("getting absolute path: %w", err)
	}

	outputFile := opts.OutputFile
	if outputFile == "" {
		outputFile = "cmd/server/services_gen.go"
	}

	// Read module name from go.mod
	moduleName, _, err := files.GetModuleInfo(serviceDirAbs)
	if err != nil {
		return fmt.Errorf("reading module name: %w", err)
	}

	// Discover services
	services, err := discoverServices(serviceDir)
	if err != nil {
		return fmt.Errorf("discovering services: %w", err)
	}

	// Generate the imports file
	code := generateImportsFile(moduleName, serviceDir, services)

	// Write to file
	if err := os.WriteFile(outputFile, []byte(code), 0644); err != nil {
		return fmt.Errorf("writing file: %w", err)
	}

	fmt.Printf("Generated %s with %d service(s): %v\n", outputFile, len(services), services)
	return nil
}

func discoverServices(servicesDir string) ([]string, error) {
	var services []string

	// Check if directory exists
	if _, err := os.Stat(servicesDir); os.IsNotExist(err) {
		fmt.Printf("Services directory does not exist: '%s'\n", servicesDir)
		return services, nil
	}

	// Walk the directory tree to find all service config files (setup/config.yml)
	err := filepath.Walk(servicesDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip if not a file or not the service config file
		if info.IsDir() || info.Name() != ServiceConfigFile {
			return nil
		}

		// Check that this is in a setup/ directory
		setupDir := filepath.Dir(path)
		if filepath.Base(setupDir) != "setup" {
			return nil
		}

		// Get the service directory (parent of setup/)
		svcDir := filepath.Dir(setupDir)

		// Get the relative path from servicesDir
		relPath, err := filepath.Rel(servicesDir, svcDir)
		if err != nil {
			return err
		}

		// Add the service path (e.g., "foo", "adyen/v70", "adyen/v71")
		services = append(services, relPath)
		return nil
	})

	if err != nil {
		return nil, fmt.Errorf("failed to walk services directory: %w", err)
	}

	return services, nil
}

func generateImportsFile(moduleName, servicesDir string, services []string) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by connexions. DO NOT EDIT.\n\n")
	sb.WriteString("package main\n\n")

	if len(services) > 0 {
		sb.WriteString("import (\n")
		for _, service := range services {
			fmt.Fprintf(&sb, "\t_ \"%s/%s/%s\"\n", moduleName, servicesDir, service)
		}
		sb.WriteString(")\n")
	}

	return sb.String()
}
