// Code generated by oapi-codegen. DO NOT EDIT.

package types

import (
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type GetPetByIDPath struct {
	PetID int64 `json:"petId" validate:"required"`
}

func (g GetPetByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type UpdatePetWithFormPath struct {
	PetID int64 `json:"petId" validate:"required"`
}

func (u UpdatePetWithFormPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type DeletePetPath struct {
	PetID int64 `json:"petId" validate:"required"`
}

func (d DeletePetPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type UploadFilePath struct {
	PetID int64 `json:"petId" validate:"required"`
}

func (u UploadFilePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type GetOrderByIDPath struct {
	OrderID int64 `json:"orderId" validate:"required"`
}

func (g GetOrderByIDPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type DeleteOrderPath struct {
	OrderID int64 `json:"orderId" validate:"required"`
}

func (d DeleteOrderPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}

type GetUserByNamePath struct {
	Username string `json:"username" validate:"required"`
}

func (g GetUserByNamePath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(g))
}

type UpdateUserPath struct {
	Username string `json:"username" validate:"required"`
}

func (u UpdateUserPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(u))
}

type DeleteUserPath struct {
	Username string `json:"username" validate:"required"`
}

func (d DeleteUserPath) Validate() error {
	return runtime.ConvertValidatorError(typesValidator.Struct(d))
}
