app:
  port: 2200
services:
  petstore:
    contexts:
      petstore:

    latency: 50ms
    errors:
      chance: 10%
      codes:
        400: 50%
        401: 25%
        403: 25%

    cache:
      schema: true

    requestTransformer: PetstoreBefore
    responseTransformer: PetstoreAfter
