app:
  port: 2200
services:
  petstore:
    contexts:
      petstore:

    latencies:
      p50: 10ms
      p99: 50ms

    errors:
      p5: 400
      p10: 401
      p25: 403

    cache:
      schema: true

    requestTransformer: PetstoreBefore
    responseTransformer: PetstoreAfter
