// Code generated by gen-service. DO NOT EDIT.

package handler

import (
	"log/slog"
	"time"

	"github.com/cubahno/connexions/v2/pkg/config"
	"github.com/cubahno/connexions/v2/pkg/typedef"
	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/codegen"
)

// NewRegistry creates a typedef registry from the OpenAPI spec bytes.
// This is called once at service initialization to build the operations registry.
// If specOptions.LazyLoad is true, operations are parsed on-demand for faster startup.
// Only operations that have generated handlers (filtered by codegen config) are built.
func NewRegistry(openapiSpec []byte, cfg codegen.Configuration, specOptions *config.SpecOptions) typedef.OperationRegistry {
	if specOptions != nil && specOptions.LazyLoad {
		return newLazyRegistry(openapiSpec, cfg, specOptions)
	}
	return newEagerRegistry(openapiSpec, cfg, specOptions)
}

// newLazyRegistry creates a lazy registry that parses operations on-demand.
func newLazyRegistry(openapiSpec []byte, cfg codegen.Configuration, specOptions *config.SpecOptions) typedef.OperationRegistry {
	start := time.Now()
	slog.Info("Creating lazy registry", "service", "spoonacular")

	registry, err := typedef.NewLazyTypeDefinitionRegistry(openapiSpec, cfg, specOptions)
	if err != nil {
		panic("failed to create lazy registry: " + err.Error())
	}

	slog.Info("Lazy registry created", "service", "spoonacular", "duration", time.Since(start), "routes", len(registry.GetRouteInfo()))
	return registry
}

// newEagerRegistry creates a registry that parses all operations at startup.
func newEagerRegistry(openapiSpec []byte, cfg codegen.Configuration, specOptions *config.SpecOptions) typedef.OperationRegistry {
	start := time.Now()
	slog.Info("Parsing OpenAPI spec", "service", "spoonacular")

	parseCtx, errs := typedef.CreateParseContext(openapiSpec, cfg, specOptions)
	if len(errs) > 0 {
		panic("failed to parse OpenAPI spec: " + errs[0].Error())
	}

	slog.Info("OpenAPI spec parsed", "service", "spoonacular", "duration", time.Since(start), "operations", len(parseCtx.Operations))

	start = time.Now()
	slog.Info("Building typedef registry", "service", "spoonacular")
	registry := typedef.NewTypeDefinitionRegistry(parseCtx, 0, openapiSpec)
	slog.Info("Typedef registry built", "service", "spoonacular", "duration", time.Since(start))

	return registry
}
