swagger: '2.0'
info:
  title: Recursive API
  version: 1.0.0
paths:
  /users:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: requestBody
          in: body
          description: Request Body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/User'
definitions:
  User:
    description: info.
  Address:
    properties:
      city:
        $ref: "#/definitions/Address"
    required:
      - city
