// Code generated by connexions. DO NOT EDIT.
// Minimal standalone server for Service service.

package main

import (
	"errors"
	"fmt"
	"log"
	"log/slog"
	"net/http"
	"os"
	"time"

	handler "github.com/cubahno/connexions/v2/examples/commands/service/zero-endpoints"
	"github.com/cubahno/connexions/v2/pkg/api"
)

func main() {
	// Setup logging
	logLevel := slog.LevelInfo
	if os.Getenv("LOG_LEVEL") == "debug" {
		logLevel = slog.LevelDebug
	}
	slogHandler := slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: logLevel})
	logger := slog.New(slogHandler)
	slog.SetDefault(logger)

	// Create the central router with middleware
	router := api.NewRouter()

	_ = api.CreateHealthRoutes(router)
	_ = api.CreateHomeRoutes(router)
	_ = api.CreateServiceRoutes(router)

	// Register this service directly
	handler.RegisterAPIRouter(router)

	// Configure server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	addr := fmt.Sprintf(":%s", port)

	server := &http.Server{
		Addr:         addr,
		Handler:      router,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  30 * 2 * time.Second,
	}

	log.Printf("Starting Service server on %s", addr)
	if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatalf("Server failed to start: %v", err)
	}
}
