// Code generated by gen-service. DO NOT EDIT.

package handler

import (
	"sync"

	"github.com/cubahno/connexions/v2/pkg/api"
	"github.com/cubahno/connexions/v2/pkg/generator"
	"github.com/cubahno/connexions/v2/pkg/schema"
	"github.com/cubahno/connexions/v2/pkg/typedef"
)

// ResponseData wraps the generated response.
type ResponseData struct {
	Body    []byte
	Headers map[string][]string
	IsError bool
}

// serviceInterface defines the interface for mock generation.
type serviceInterface interface {
	talkToChatbot(path, method string) (*ResponseData, error)
	getConversationSuggests(path, method string) (*ResponseData, error)
	searchCustomFoods(path, method string) (*ResponseData, error)
	detectFoodInText(path, method string) (*ResponseData, error)
	imageAnalysisByURL(path, method string) (*ResponseData, error)
	imageClassificationByURL(path, method string) (*ResponseData, error)
	autocompleteIngredientSearch(path, method string) (*ResponseData, error)
	computeGlycemicLoad(path, method string) (*ResponseData, error)
	mapIngredientsToGroceryProducts(path, method string) (*ResponseData, error)
	ingredientSearch(path, method string) (*ResponseData, error)
	getIngredientSubstitutes(path, method string) (*ResponseData, error)
	computeIngredientAmount(path, method string) (*ResponseData, error)
	getIngredientInformation(path, method string) (*ResponseData, error)
	getIngredientSubstitutesByID(path, method string) (*ResponseData, error)
	getARandomFoodJoke(path, method string) (*ResponseData, error)
	searchMenuItems(path, method string) (*ResponseData, error)
	autocompleteMenuItemSearch(path, method string) (*ResponseData, error)
	getMenuItemInformation(path, method string) (*ResponseData, error)
	menuItemNutritionLabelWidget(path, method string) (*ResponseData, error)
	menuItemNutritionLabelImage(path, method string) (*ResponseData, error)
	visualizeMenuItemNutritionByID(path, method string) (*ResponseData, error)
	menuItemNutritionByIDImage(path, method string) (*ResponseData, error)
	classifyGroceryProduct(path, method string) (*ResponseData, error)
	classifyGroceryProductBulk(path, method string) (*ResponseData, error)
	searchGroceryProducts(path, method string) (*ResponseData, error)
	autocompleteProductSearch(path, method string) (*ResponseData, error)
	searchGroceryProductsByUPC(path, method string) (*ResponseData, error)
	getComparableProducts(path, method string) (*ResponseData, error)
	getProductInformation(path, method string) (*ResponseData, error)
	productNutritionLabelWidget(path, method string) (*ResponseData, error)
	productNutritionLabelImage(path, method string) (*ResponseData, error)
	visualizeProductNutritionByID(path, method string) (*ResponseData, error)
	productNutritionByIDImage(path, method string) (*ResponseData, error)
	searchRestaurants(path, method string) (*ResponseData, error)
	searchAllFood(path, method string) (*ResponseData, error)
	searchSiteContent(path, method string) (*ResponseData, error)
	getRandomFoodTrivia(path, method string) (*ResponseData, error)
	searchFoodVideos(path, method string) (*ResponseData, error)
	getWineDescription(path, method string) (*ResponseData, error)
	getDishPairingForWine(path, method string) (*ResponseData, error)
	getWinePairing(path, method string) (*ResponseData, error)
	getWineRecommendation(path, method string) (*ResponseData, error)
	generateMealPlan(path, method string) (*ResponseData, error)
	clearMealPlanDay(path, method string) (*ResponseData, error)
	addToMealPlan(path, method string) (*ResponseData, error)
	deleteFromMealPlan(path, method string) (*ResponseData, error)
	getShoppingList(path, method string) (*ResponseData, error)
	addToShoppingList(path, method string) (*ResponseData, error)
	deleteFromShoppingList(path, method string) (*ResponseData, error)
	generateShoppingList(path, method string) (*ResponseData, error)
	getMealPlanTemplates(path, method string) (*ResponseData, error)
	addMealPlanTemplate(path, method string) (*ResponseData, error)
	getMealPlanTemplate(path, method string) (*ResponseData, error)
	deleteMealPlanTemplate(path, method string) (*ResponseData, error)
	getMealPlanWeek(path, method string) (*ResponseData, error)
	analyzeRecipe(path, method string) (*ResponseData, error)
	analyzeRecipeInstructions(path, method string) (*ResponseData, error)
	autocompleteRecipeSearch(path, method string) (*ResponseData, error)
	searchRecipes(path, method string) (*ResponseData, error)
	convertAmounts(path, method string) (*ResponseData, error)
	classifyCuisine(path, method string) (*ResponseData, error)
	extractRecipeFromWebsite(path, method string) (*ResponseData, error)
	searchRecipesByIngredients(path, method string) (*ResponseData, error)
	searchRecipesByNutrients(path, method string) (*ResponseData, error)
	guessNutritionByDishName(path, method string) (*ResponseData, error)
	getRecipeInformationBulk(path, method string) (*ResponseData, error)
	parseIngredients(path, method string) (*ResponseData, error)
	analyzeARecipeSearchQuery(path, method string) (*ResponseData, error)
	quickAnswer(path, method string) (*ResponseData, error)
	getRandomRecipes(path, method string) (*ResponseData, error)
	visualizeEquipment(path, method string) (*ResponseData, error)
	visualizeIngredients(path, method string) (*ResponseData, error)
	visualizeRecipeNutrition(path, method string) (*ResponseData, error)
	visualizePriceBreakdown(path, method string) (*ResponseData, error)
	createRecipeCard(path, method string) (*ResponseData, error)
	visualizeRecipeTaste(path, method string) (*ResponseData, error)
	getAnalyzedRecipeInstructions(path, method string) (*ResponseData, error)
	createRecipeCardGet(path, method string) (*ResponseData, error)
	visualizeRecipeEquipmentByID(path, method string) (*ResponseData, error)
	getRecipeEquipmentByID(path, method string) (*ResponseData, error)
	equipmentByIDImage(path, method string) (*ResponseData, error)
	getRecipeInformation(path, method string) (*ResponseData, error)
	visualizeRecipeIngredientsByID(path, method string) (*ResponseData, error)
	getRecipeIngredientsByID(path, method string) (*ResponseData, error)
	ingredientsByIDImage(path, method string) (*ResponseData, error)
	recipeNutritionLabelWidget(path, method string) (*ResponseData, error)
	recipeNutritionLabelImage(path, method string) (*ResponseData, error)
	visualizeRecipeNutritionByID(path, method string) (*ResponseData, error)
	getRecipeNutritionWidgetByID(path, method string) (*ResponseData, error)
	recipeNutritionByIDImage(path, method string) (*ResponseData, error)
	visualizeRecipePriceBreakdownByID(path, method string) (*ResponseData, error)
	getRecipePriceBreakdownByID(path, method string) (*ResponseData, error)
	priceBreakdownByIDImage(path, method string) (*ResponseData, error)
	getSimilarRecipes(path, method string) (*ResponseData, error)
	summarizeRecipe(path, method string) (*ResponseData, error)
	visualizeRecipeTasteByID(path, method string) (*ResponseData, error)
	getRecipeTasteByID(path, method string) (*ResponseData, error)
	recipeTasteByIDImage(path, method string) (*ResponseData, error)
	connectUser(path, method string) (*ResponseData, error)
	generateRequest(req *api.GenerateRequest, op *schema.Operation) []byte
	generateError(path, method string, errMsg string) []byte
}

// operationData holds cached operation and response schema for a single endpoint.
type operationData struct {
	operation      *schema.Operation
	responseSchema *schema.ResponseSchema
}

// service implements serviceInterface with mock generation logic.
type service struct {
	generator generator.Generate
	registry  typedef.OperationRegistry

	// Cached operation data (lazy loaded)
	opCache sync.Map // map[string]*operationData
}

// newService creates a new service instance.
func newService(contextsSrc []byte, defaultContexts []map[string]map[string]any, registry typedef.OperationRegistry) (*service, error) {
	orderedCtx := generator.LoadServiceContext(contextsSrc, defaultContexts)

	gen, err := generator.NewGenerator(orderedCtx)
	if err != nil {
		return nil, err
	}

	return &service{
		generator: gen,
		registry:  registry,
	}, nil
}

// Ensure service implements serviceInterface.
var _ serviceInterface = (*service)(nil)

// getOperationData returns cached operation data, loading it lazily if needed.
func (s *service) getOperationData(path, method string) *operationData {
	key := method + ":" + path

	// Check cache first
	if cached, ok := s.opCache.Load(key); ok {
		return cached.(*operationData)
	}

	// Load from registry
	op := s.registry.FindOperation(path, method)
	if op == nil {
		return nil
	}

	// Build response schema
	respSchema := &schema.ResponseSchema{}
	if successResp := op.Response.GetSuccess(); successResp != nil {
		respSchema.ContentType = successResp.ContentType
		respSchema.Body = successResp.Content
		respSchema.Headers = successResp.Headers
	}
	if errResp := op.Response.GetResponse(400); errResp != nil {
		respSchema.Error = errResp.Content
	}

	data := &operationData{
		operation:      op,
		responseSchema: respSchema,
	}

	s.opCache.Store(key, data)
	return data
}

func (s *service) generateRequest(req *api.GenerateRequest, op *schema.Operation) []byte {
	if op == nil {
		opData := s.getOperationData(req.Path, req.Method)
		if opData != nil {
			op = opData.operation
		}
	}
	return s.generator.Request(req, op)
}

func (s *service) generateError(path, method string, errMsg string) []byte {
	opData := s.getOperationData(path, method)
	if opData != nil && opData.responseSchema.Error != nil {
		opKey := method + ":" + path
		return s.generator.Error(opData.responseSchema.Error, errorPaths[opKey], errMsg)
	}
	return []byte(errMsg)
}

func (s *service) talkToChatbot(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getConversationSuggests(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchCustomFoods(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) detectFoodInText(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) imageAnalysisByURL(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) imageClassificationByURL(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) autocompleteIngredientSearch(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) computeGlycemicLoad(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) mapIngredientsToGroceryProducts(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) ingredientSearch(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getIngredientSubstitutes(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) computeIngredientAmount(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getIngredientInformation(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getIngredientSubstitutesByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getARandomFoodJoke(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchMenuItems(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) autocompleteMenuItemSearch(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getMenuItemInformation(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) menuItemNutritionLabelWidget(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) menuItemNutritionLabelImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeMenuItemNutritionByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) menuItemNutritionByIDImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) classifyGroceryProduct(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) classifyGroceryProductBulk(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchGroceryProducts(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) autocompleteProductSearch(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchGroceryProductsByUPC(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getComparableProducts(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getProductInformation(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) productNutritionLabelWidget(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) productNutritionLabelImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeProductNutritionByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) productNutritionByIDImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchRestaurants(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchAllFood(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchSiteContent(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRandomFoodTrivia(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchFoodVideos(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getWineDescription(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getDishPairingForWine(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getWinePairing(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getWineRecommendation(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) generateMealPlan(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) clearMealPlanDay(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) addToMealPlan(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) deleteFromMealPlan(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getShoppingList(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) addToShoppingList(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) deleteFromShoppingList(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) generateShoppingList(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getMealPlanTemplates(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) addMealPlanTemplate(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getMealPlanTemplate(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) deleteMealPlanTemplate(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getMealPlanWeek(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) analyzeRecipe(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) analyzeRecipeInstructions(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) autocompleteRecipeSearch(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchRecipes(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) convertAmounts(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) classifyCuisine(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) extractRecipeFromWebsite(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchRecipesByIngredients(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) searchRecipesByNutrients(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) guessNutritionByDishName(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRecipeInformationBulk(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) parseIngredients(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) analyzeARecipeSearchQuery(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) quickAnswer(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRandomRecipes(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeEquipment(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeIngredients(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeRecipeNutrition(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizePriceBreakdown(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) createRecipeCard(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeRecipeTaste(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getAnalyzedRecipeInstructions(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) createRecipeCardGet(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeRecipeEquipmentByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRecipeEquipmentByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) equipmentByIDImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRecipeInformation(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeRecipeIngredientsByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRecipeIngredientsByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) ingredientsByIDImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) recipeNutritionLabelWidget(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) recipeNutritionLabelImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeRecipeNutritionByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRecipeNutritionWidgetByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) recipeNutritionByIDImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeRecipePriceBreakdownByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRecipePriceBreakdownByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) priceBreakdownByIDImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getSimilarRecipes(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) summarizeRecipe(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) visualizeRecipeTasteByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) getRecipeTasteByID(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) recipeTasteByIDImage(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}

func (s *service) connectUser(path, method string) (*ResponseData, error) {
	opData := s.getOperationData(path, method)
	if opData == nil {
		return nil, nil
	}

	res := s.generator.Response(opData.responseSchema)
	return &ResponseData{
		Body:    res.Body,
		Headers: res.Headers,
		IsError: res.IsError,
	}, nil
}
